// =============================================
//  WeeklyReport — Full Behaviour Report
// =============================================

import { Card }        from '../components/Card'
import { ScoreRing }   from '../components/ScoreRing'
import { ProgressBar } from '../components/ProgressBar'
import { WEEKLY }      from '../data/mockData'
import styles          from './WeeklyReport.module.css'

const INSIGHT_STYLES = {
  critical:   { border: 'var(--red)',    bg: '#ef444412', tagColor: '#ef4444' },
  trend:      { border: 'var(--amber)',  bg: '#f59e0b12', tagColor: '#f59e0b' },
  win:        { border: 'var(--green)',  bg: '#10b98112', tagColor: '#10b981' },
  prediction: { border: 'var(--accent-glow)', bg: '#7c3aed12', tagColor: '#a855f7' },
}

export function WeeklyReport() {
  return (
    <div style={{ maxWidth: 660 }}>
      {/* Header */}
      <Card>
        <div className={styles.topRow}>
          <ScoreRing score={WEEKLY.bsi} size={140} />
          <div>
            <div className={styles.weekLabel}>Week of Feb 24 – Mar 2, 2025</div>
            <div className={styles.verdict}>Good Progress 📈</div>
            <p className={styles.verdictDesc}>
              You maintained {WEEKLY.workoutsHit}/{WEEKLY.workoutsGoal} workout sessions this week.
              Sleep consistency improved by 12%. Hydration remains your biggest risk area
              — address this next week.
            </p>
            <div className={styles.statRow}>
              <StatChip label="Gym Hit"    value={`${WEEKLY.workoutsHit}/${WEEKLY.workoutsGoal}`} color="var(--green)"  />
              <StatChip label="Gym Rate"   value={`${Math.round(WEEKLY.workoutsHit / WEEKLY.workoutsGoal * 100)}%`} color="var(--accent-glow)" />
              <StatChip label="Pred. Acc." value={`${WEEKLY.predictions}%`} color="var(--cyan)"   />
            </div>
          </div>
        </div>
      </Card>

      {/* Habit Consistency Scores */}
      <Card title="Habit Consistency Scores" icon="📊">
        <ProgressBar label="Overall Consistency" pct={WEEKLY.consistency} color="var(--accent-glow)" />
        <ProgressBar label="Sleep Quality"        pct={WEEKLY.sleep}       color="#6366f1" />
        <ProgressBar label="Hydration"            pct={WEEKLY.hydration}   color="var(--cyan)" />
        <ProgressBar label="Mood Stability"       pct={WEEKLY.mood}        color="var(--amber)" />
        <ProgressBar label="Nutrition Score"      pct={WEEKLY.nutrition}   color="#ec4899" />
        <ProgressBar label="AI Pred. Accuracy" pct={WEEKLY.predictions} color="var(--green)" subtitle="Model: Composite (LR + RF + LSTM)" />
      </Card>

      {/* Pattern Insights */}
      <Card title="Risk Patterns Detected" icon="🔍">
        {WEEKLY.insights.map((insight, i) => {
          const s = INSIGHT_STYLES[insight.type]
          return (
            <div
              key={i}
              className={styles.insightCard}
              style={{ borderLeft: `3px solid ${s.border}`, background: s.bg }}
            >
              <span className={styles.insightIcon}>{insight.icon}</span>
              <div>
                <div
                  className={styles.insightTag}
                  style={{ background: s.tagColor + '25', color: s.tagColor }}
                >
                  {insight.tag}
                </div>
                <div className={styles.insightText}>{insight.text}</div>
              </div>
            </div>
          )
        })}
      </Card>

      {/* AI Recommendation */}
      <Card title="AI's #1 Recommendation" icon="🤖">
        <div className={styles.reco}>
          <div className={styles.recoIcon}>💡</div>
          <p className={styles.recoText}>{WEEKLY.recommendation}</p>
        </div>
        <div className={styles.recoFooter}>
          Generated by AI · Based on 7 days of behavioural data · Personalised to Rajan
        </div>
      </Card>

      {/* Next week goals */}
      <Card title="Next Week's AI-Set Goals" icon="🎯">
        {[
          { goal: 'Sleep 7h+ on Sunday & Tuesday',       impact: 'Cuts gym skip risk by ~40%', color: 'var(--indigo)' },
          { goal: 'Drink 500ml water after every 5k steps', impact: 'Prevents hydration drop pattern', color: 'var(--cyan)'   },
          { goal: 'Healthy snack prepped by 6 PM on weekdays', impact: 'Intercepts 79% junk craving window', color: 'var(--green)'  },
          { goal: 'Log mood every morning',               impact: 'Improves prediction accuracy by ~15%', color: 'var(--amber)' },
        ].map((g, i) => (
          <div key={i} className={styles.goalRow}>
            <div className={styles.goalDot} style={{ background: g.color }} />
            <div>
              <div className={styles.goalText}>{g.goal}</div>
              <div className={styles.goalImpact}>{g.impact}</div>
            </div>
          </div>
        ))}
      </Card>
    </div>
  )
}

function StatChip({ label, value, color }) {
  return (
    <div className={styles.statChip}>
      <div className={styles.statValue} style={{ color }}>{value}</div>
      <div className={styles.statLabel}>{label}</div>
    </div>
  )
}
